name: "DEV Infra - Terraform Plan"

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform-plan-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Asumir IAM Role via OIDC
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 2. Ejecutar comandos Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          terraform -chdir=src/environments/dev init \
            -backend-config="bucket=${{ secrets.BACKEND_BUCKET }}" \
            -backend-config="key=${{ secrets.BACKEND_KEY }}" \
            -backend-config="region=${{ secrets.AWS_REGION }}" \
            -backend-config="use_lockfile=true" \
            -backend-config="encrypt=true"

      - name: Terraform Validate
        run: terraform -chdir=src/environments/dev validate

      - name: Terraform Plan
        run: terraform -chdir=src/environments/dev plan -var-file="../../../config/dev/dev.tfvars"
